drop table field_data_field_birth_date;
drop table field_data_field_death_date;
drop table field_data_field_relationships;
drop table field_data_field_relationship_type;
drop table field_revision_field_birth_date;
drop table field_revision_field_death_date;
drop table field_revision_field_relationships;
drop table field_revision_field_relationship_type;
